receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "localhost:4317"
exporters:
  logging:
    loglevel: debug
  datadog:
    api:
      key: "<DATADOG_API_KEY>"

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [logging, datadog]
  telemetry:
    metrics:
      address: localhost:8888
